name: Library Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Library Build
    runs-on: windows-latest
    env:
      REPOSITORY_URL: https://github.com/Oliver721003/tsa-text-helper
    steps:
      - uses: actions/checkout@v3.1
      - uses: NuGet/setup-nuget@v1.0.7
      - uses: microsoft/setup-msbuild@v1.1
      - name: Package Restore
        run: |
          nuget restore
      - name: Component Deploy
        run: |
          msbuild.exe /p:Configuration=Release
