name: Library Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Library Build And Testing
    runs-on: windows-latest
    env:
      REPOSITORY_URL: https://github.com/Oliver721003/tsa-text-helper
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: NuGet/setup-nuget@v1.0.7
      - uses: microsoft/setup-msbuild@v1.1
      - name: Package Restore
        run: |
          nuget restore
      - name: Library Build
        run: |
          msbuild.exe /p:Configuration=Debug
      - name: Install NUnit.ConsoleRunner
        run: |
          nuget install NUnit.ConsoleRunner -Version 3.15.2 -DirectDownload -OutputDirectory .
      - name: Run Unit Testing
        run: |
          ./NUnit.ConsoleRunner.3.15.2/tools/nunit3-console.exe TextHelper.Tests/bin/Debug/TextHelper.Tests.dll
  deploy:
    name: Library Deploy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.1
      - uses: NuGet/setup-nuget@v1.0.7
      - uses: microsoft/setup-msbuild@v1.1
      - name: Package Restore
        run: |
          nuget restore
      - name: Library Deploy
        run: |
          msbuild.exe /p:Configuration=Release
